name: da-band

services:
  api:
    ports:
      - "8000:8000"
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
