services:
  api:
    profiles: ["default"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  api-dev:
    profiles: ["dev"]
    build:
      target: dev
    volumes: 
      - .:/app # hot reload

  api-prod:
    profiles: ["prod"]
    build:
      target: prod
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
